#optional settings for a boss-bar title at the top
event-title-name: "Fishing Event" #optional, specifying this will generate a bossbar, leaving it out won't
event-title-colour: "PURPLE" #required if event-title-name is specified

#optional messages to appear in chat at the start and end of events
event-start-message: "It's time to fish >:D" #optional
event-end-message: "No more fishing :(" #optional

#settings for when to schedule regular events- default values are event-frequency="1d", event-duration="1h"
#how often to schedule an event:
event-frequency: "60s" #required

#how long an event should last for (must be less than event-frequency, or default values are used):
event-duration: "30s" #required

#what time to schedule the first event after the plugin is loaded, specified in UTC time. The first event occurs at the next occurrence of this time
#on a clock e.g. if it is 21:00 UTC, event-start-time="22:00" will schedule the first event for today at 22:00, but event-start-time="20:00" will schedule the
#first event for tomorrow at 20:00
event-start-time: "01:50" #optional, will start immediately if not specified

#optional, plugin will use only custom fish if there are any, or only normal fish if there aren't. I may change this so that not only custom fish are used if there are any, or so that exclusively custom fish can be chosen if there are any
# e.g. exclusively-custom-fish: true
fish:
   - name: Tuna
     minlength: 12
     maxlength: 20
     rarity: 0.5
     item: salmon